name: Release

on:
  release:
    types: [created]

jobs:
  publish-cli:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: macos-12
    steps:
      - name: Set up Go 1.21.5
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - id: get_version
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed -nE 's!refs/tags/!!p')
          echo "release_version=$(RELEASE_VERSION)" >> $GITHUB_OUTPUT
      - name: Compile binaries
        run: |
          chmod +x ./hack/build.sh
          ./hack/build.sh
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.release_version }}
      - name: Save release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
